<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Обработка-и-анализ-данных-в-Numpy-массивах" data-toc-modified-id="Обработка-и-анализ-данных-в-Numpy-массивах-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Обработка и анализ данных в Numpy-массивах</a></span></li></ul></div>




# Обработка и анализ данных в Numpy-массивах

<p style="font-size:125%; color:#119988; background-color:#EEE">Задание 1</p>

Дано: списки `a,b=[1,1,1],[3,3,3]`

Создать одномерные массивы A и B из списков а и b.

Вычислить выражение $-((B-А)*(B/2))$

In [2]:
import numpy as np

In [3]:
#1 Ваш код здесь
a = [1,1,1]
b = [3,3,3]
A = np.array(a)
B = np.array(b)
result = -((B-A)*(B/2))
print(result)


[-3. -3. -3.]


<p style="font-size:125%; color:#119988; background-color:#EEE">Задание 2</p>

Используя как можно меньше операций в исходном массиве "шахматная доска" np.zeros((8,8)), добиться расстановки кодов "шахматных фигур".

Ожидаемый результат:
```
[[-4., -3., -2., -6., -5., -2., -3., -4.],
 [-1., -1., -1., -1., -1., -1., -1., -1.],
 [0., 0., 0., 0., 0., 0., 0., 0.],
 [0., 0., 0., 0., 0., 0., 0., 0.],
 [0., 0., 0., 0., 0., 0., 0., 0.],
 [0., 0., 0., 0., 0., 0., 0., 0.],
 [1., 1., 1., 1., 1., 1., 1., 1.],
 [4., 3., 2., 6., 5., 2., 3., 4.]]
 ```

In [9]:
#2. Ваш код здесь
board = np.zeros((8,8))

board[0] = [-4,-3,-2,-6,-5,-2,-3,-4]
board[1] = [-1]*8
board[6] = [1]*8
board [7] = [4,3,2,6,5,2,3,4]
print(board)

[[-4. -3. -2. -6. -5. -2. -3. -4.]
 [-1. -1. -1. -1. -1. -1. -1. -1.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.]
 [ 4.  3.  2.  6.  5.  2.  3.  4.]]


<p style="font-size:125%; color:#119988; background-color:#EEE">Задание 3</p>

Средствами NumPy рассчитать произведения четных чисел от 2 до 20 на ближайшие к ним бОльшие нечетные числа

In [10]:
# 3. Ваш код здесь
even_numbers = np.arange(2,21,2)
odd_numbers = even_numbers+1
product = even_numbers*odd_numbers
print(product)

[  6  20  42  72 110 156 210 272 342 420]


<p style="font-size:125%; color:#119988; background-color:#EEE">Задание 4</p>

Сгенерировать двумерный массив *arr* размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в дипазоне от 0 до 20. Нормализовать значения массива так, что после нормализации максимальный элемент масива будет равен 1.0, минимальный 0.0. Значения округлить (с помощью `np.round()`) до четырех десятичных знаков.

In [14]:
# 4. Ваш код здесь
arr = np.random.uniform(0,20,size=(4,7))
arr_normalized = (arr-np.min(arr)/np.max(arr)-np.min(arr))
arr_normalized_rand = np.round(arr_normalized, decimals=4)
print(arr_normalized_rand)



[[ 2.25980e+00  5.77190e+00  1.87474e+01 -9.00000e-04  8.79610e+00
   3.75390e+00  1.42660e+00]
 [ 4.78450e+00  4.27490e+00  1.94580e+01  1.87756e+01  1.46605e+01
   1.20508e+01  1.37963e+01]
 [ 1.42819e+01  1.37609e+01  4.44210e+00  1.19920e+01  1.38750e+00
   1.48744e+01  6.52930e+00]
 [ 5.13000e+00  4.25940e+00  1.46910e+00  8.14780e+00  2.63350e+00
   1.74377e+01  5.18070e+00]]


<p style="font-size:125%; color:#119988; background-color:#EEE">Задание 5</p>

5. Имеется массив my_array
```
my_array = np.array([[1,2,3,4,5],
                [6,7,8,9,10],
                [11,12,13,14,15],
                [16,17,18,19,20],
                [21,22,23,24,25]])
```
Напишите код, с помощью которого можно извлечь из него центральный фрагмент размером 3 х 3, с числами 7, 8, 9, 12, 13, 14, 17, 18, 19.

In [16]:
# 5. Ваш код здесь

my_array = np.array([[1,2,3,4,5],
             [6,7,8,9,10],
             [11,12,13,14,15],
             [16,17,18,19,20],
             [21,22,23,24,25]])
ceral_fragment = my_array[1:4,1:4]
print(ceral_fragment)





[[ 7  8  9]
 [12 13 14]
 [17 18 19]]


<p style="font-size:125%; color:#119988; background-color:#EEE">Задание 6</p>

Создайте массив *my_sin*, состоящий из синусов элементов массива *my_array*.
Посчитайте, чему равна сумма элементов полученного массива. Ответ округлите до
трёх цифр после запятой.

In [20]:
# 6. Ваш код здесь
my_array = np.array ([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25]])
sin_my_array = np.sin(my_array)
sum_sin = np.sum(sin_my_array)
round_sum = round(sum_sin,3)
print(round_sum)


0.725


<p style="font-size:125%; color:#119988; background-color:#EEE">Задание 7</p>

Создать матрицу из 20 случайных целых чисел от 0 до 100. Получить второе сверху значение в матрице. Определить индекс этого значения.

In [26]:
# 7. Ваш код здесь
matrix = np.random.randint(0,101, size=(4,5))
second_matrix = matrix[1,0]
indexc = np.argwhere(matrix == second_matrix)
print("Матрица: ")
print(matrix)
print("Второе сверху значение: ",second_matrix)
print("Индекс второго значения: ",indexc)


Матрица: 
[[79 14 39 38 34]
 [75 42 94 95 63]
 [48 28 70 68 71]
 [23 25 87 43 11]]
Второе сверху значение:  75
Индекс второго значения:  [[1 0]]


<p style="font-size:125%; color:#119988; background-color:#EEE">Задание 8</p>

Задать два двухмерных массива *ar1* и *ar2* размерности (4, 7), состоящих из случайных целых чисел в пределах от 0 до 10. Построить двухмерный массив размерности (4, 7), каждый элемент которого представляет собой максимум (минимум, среднее) из двух значений, находящихся на аналогичной позиции в массивах *ar1*, *ar2*.

In [3]:
# 8. Ваш код здесь
ar1 = np.random.randint(0, 10, (4, 7))
ar2 = np.random.randint(0, 10, (4, 7))
maximum_array = np.maximum(ar1, ar2)
minimum_array = np.minimum(ar1, ar2)
average_array = (ar1 + ar2) / 2
combined_array = np.column_stack((maximum_array, minimum_array, average_array))
print(combined_array)

[[6.  8.  3.  6.  1.  7.  2.  2.  6.  1.  3.  0.  2.  1.  4.  7.  2.  4.5
  0.5 4.5 1.5]
 [2.  7.  9.  5.  5.  6.  6.  2.  3.  0.  0.  2.  6.  2.  2.  5.  4.5 2.5
  3.5 6.  4. ]
 [1.  4.  6.  2.  9.  6.  2.  0.  2.  5.  0.  6.  1.  1.  0.5 3.  5.5 1.
  7.5 3.5 1.5]
 [4.  7.  9.  1.  4.  7.  6.  1.  2.  0.  0.  2.  5.  2.  2.5 4.5 4.5 0.5
  3.  6.  4. ]]


<p style="font-size:125%; color:#119988; background-color:#EEE">Задание 9</p>

Имеется массив *great_array*
```
first = [x**(1/2) for x in range(100)]
second = [x**(1/3) for x in range(100, 200)]
third = [x/y for x in range(200,300,2) for y in [3,5]]
great_array = np.array([first, second, third]).T
```
Чему равна сумма элементов массива great_array, значение которых больше 50?

In [5]:
#9 Ваш код здесь

first = [x**(1/2) for x in range(100)]
second = [x**(1/3) for x in range(100, 200)]
third = [x/y for x in range(200,300,2) for y in [3,5]]
great_array = np.array([first, second, third]).T
sum_greater_50 = np.sum(great_array[great_array > 50])
print(sum_greater_50)





5470.0


<p style="font-size:125%; color:#119988; background-color:#EEE">Задание 10</p>

Переведите массив *great_array* в одномерную форму. Какое значение в получившемся массиве имеет элемент с индексом 150?

In [6]:
# 10. Ваш код здесь
one_dimensional_array = great_array.flatten()
value_at_index_150 = one_dimensional_array[150]
print(value_at_index_150)


7.0710678118654755


<p style="font-size:125%; color:#119988; background-color:#EEE">Задание 11</p>

Получить индексы, для которых элементы массивов A и B совпадают.
```
A = np.array([1,2,3,2,3,4,3,4,5,6])
B = np.array([7,2,10,2,7,4,9,4,9,8])
```
Ожидается результат:

```
array([1, 3, 5, 7])
```

In [12]:
# 11.
A = np.array([1,2,3,2,3,4,3,4,5,6])
B = np.array([7,2,10,2,7,4,9,4,9,8])
matching_indices = np.where(A == B)[0]
print(matching_indices)


# Ваш код здесь



<p style="font-size:125%; color:#119988; background-color:#EEE">Задание 12</p>

Создайте три массива: массив четных чисел от 2 до 20, массив ближайших к числам первого массива бОльших нечётных чисел, массив векторного произведения первого массива на второй. Соедините все массивы в один двумерный массив, расположив исходные массивы в столбцах.

In [7]:
# 12.  Ваш код здесь
even_numbers = np.arange(2, 21, 2)
closest_greater_odd_numbers = even_numbers + 1
vector_product = np.multiply(even_numbers, closest_greater_odd_numbers)
combined_array = np.column_stack((even_numbers, closest_greater_odd_numbers, vector_product))
print(combined_array)


[[  2   3   6]
 [  4   5  20]
 [  6   7  42]
 [  8   9  72]
 [ 10  11 110]
 [ 12  13 156]
 [ 14  15 210]
 [ 16  17 272]
 [ 18  19 342]
 [ 20  21 420]]
